#!/usr/bin/env bash
#
# Stage the GitHub Pages site.
#
# pages/ holds only what markdown cannot express: the landing page and the
# demo. Shared assets are copied from app/ at build time rather than duplicated
# in git, so the demo cannot drift into showing a UI that does not exist.
#
#   ./dev/build-site.sh     # populate pages/assets for local viewing
#
# CI runs this before publishing.
set -eu

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
mkdir -p "${ROOT}/pages/assets"

# Belt and braces. Publishing through the Actions path serves the artifact
# as-is and never invokes Jekyll, so this is only insurance against Pages being
# switched back to deploy-from-branch later — at which point Jekyll would
# otherwise try to build the site and choke on anything underscore-prefixed.
touch "${ROOT}/pages/.nojekyll"

cp "${ROOT}/app/assets/bitwrench.umd.min.js" "${ROOT}/pages/assets/"
cp "${ROOT}/app/assets/triops.js"            "${ROOT}/pages/assets/"
cp "${ROOT}/app/assets/triops-logo.png"      "${ROOT}/pages/assets/"
cp "${ROOT}/app/assets/favicon.ico"          "${ROOT}/pages/assets/"

# The site is static, so it cannot ask a server what version it is. Read
# TRIOPS_VERSION out of the bootstrap at build time instead — same single source
# of truth as the app and the release tag, no third place to forget to update.
#
# grep rather than php, so this script needs nothing but a shell.
VERSION="$(grep -oE "define\('TRIOPS_VERSION', *'[^']+'\)" "${ROOT}/app/lib/triops.php" \
           | grep -oE "'[0-9][^']*'" | tr -d "'")"
[ -n "$VERSION" ] || { echo "could not read TRIOPS_VERSION from app/lib/triops.php"; exit 1; }

BW_VERSION="$(head -c 200 "${ROOT}/app/assets/bitwrench.umd.min.js" \
              | grep -oE 'bitwrench v[0-9][^ |]*' | sed 's/bitwrench v//')"

cat > "${ROOT}/pages/assets/version.js" <<EOF
/* generated by dev/build-site.sh — do not edit */
window.TRIOPS_SITE = {
  version: "${VERSION}",
  bitwrench: "${BW_VERSION}",
  repo: "https://github.com/deftio/triops"
};
EOF

touch "${ROOT}/pages/.nojekyll"

echo "staged $(ls -1 "${ROOT}/pages/assets" | wc -l | tr -d ' ') assets into pages/assets/"
echo "site version ${VERSION} (bitwrench ${BW_VERSION})"
echo "open ${ROOT}/pages/index.html"
